// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "src/database/schema",
  migrations: {
    path: "src/database/schema/migrations",
    seed: "tsx src/database/seed/index.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
